# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Spring Boot Microservice template

on:
  release:
    types: [created]
    
  workflow_dispatch:

env: 
  SERVER_IDENTITY_KEYSTORE_PATH: 'src/main/resources/gunnarro-microservice.jks'
  SERVER_IDENTITY_KEYSTORE_PASS: 'test'
  SERVER_IDENTITY_KEYSTORE_ALIAS: 'gunnarro-microservice'
  GITHUB_TOKEN: ${{ secrets.ACTIONS_GITHUB_TOKEN }}

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

#    - name: download archetype
#      run: mvn -B clean install -f pom.xml -s $GITHUB_WORKSPACE/settings.xml -P github -Dmaven.repo.local=$GITHUB_WORKSPACE/.m2

#    - name: get archetype
#      run: mvn dependency:get -Dartifact=org.gunnarro.microservice:spring-boot-microservice-archetype:1.0.0-SNAPSHOT:jar:sources -s $GITHUB_WORKSPACE/settings.xml -P github -DremoteRepositories=https://maven.pkg.github.com/gunnarro/microservice-archetype

    # download all
    # - name: downlaod archetype
    #  uses: actions/download-artifact@v3
    #   with:
    #   path: ${{ github.workspace }}

    - name: Display structure of downloaded files
      run: ls -R
      working-directory: ${{ github.workspace }}

    - name: Create new microservice
      run: mvn -B -P archetype -s $GITHUB_WORKSPACE/settings-github.xml archetype:generate 
                       -DinteractiveMode=false   
                       -DarchetypeGroupId=org.gunnarro.microservice 
                       -DarchetypeArtifactId=spring-boot-microservice-archetype 
                       -DarchetypeVersion=1.0.0-SNAPSHOT 
                       -DgroupId=org.gunnarro.microservice 
                       -DartifactId=my-microservice 
                       -Dversion=1.0.0-SNAPSHOT 
                       -Dservicename=mymicroservice
                       -DoutputDirectory=target
    

        
#    - name: Test my-microservice
#      run: mvn --quiet -B clean install -f target/my-microservice/pom.xml
