# This workflow checkout gunnarro micorservice archetype from github packages, thereafter it build the microservice template, commit changes and finally test the microservice.

name: Spring Boot Microservice template

on:
  release:
    types: [created]
    
  workflow_dispatch:

env: 
  SERVER_IDENTITY_KEYSTORE_PATH: 'src/main/resources/gunnarro-microservice.jks'
  SERVER_IDENTITY_KEYSTORE_PASS: 'test'
  SERVER_IDENTITY_KEYSTORE_ALIAS: 'gunnarro-microservice'
#  GITHUB_TOKEN: ${{ secrets.ACTIONS_GITHUB_TOKEN }}

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
  
    - name: Display structure of downloaded files
      run: ls -R
      working-directory: ${{ github.workspace }}

    - name: Create new microservice
      run: mvn -B -s $GITHUB_WORKSPACE/settings-github.xml archetype:generate 
                       -DinteractiveMode=false   
                       -DarchetypeGroupId=org.gunnarro.microservice 
                       -DarchetypeArtifactId=spring-boot-microservice-archetype 
                       -DarchetypeVersion=1.0.0-SNAPSHOT 
                       -DgroupId=org.gunnarro.microservice 
                       -DartifactId=my-microservice 
                       -Dversion=1.0.0-SNAPSHOT 
                       -Dservicename=mymicroservice
                       -DoutputDirectory=target
      env:
        GITHUB_TOKEN: ${{ secrets.ACTIONS_GITHUB_TOKEN }}
        GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}    
        
    - name: copy generated sorce code
      run: | 
        rsync -rv target/my-microservice/src/* ${{ github.workspace }}/src
    
    - name: Display updated src dir
      run: | 
        ls -R ${{ github.workspace }}/src
    
    - name: Git add changed files
      run: |
        pwd
        git add ${{ github.workspace }}/src/
        git status
     
    - name: commit and push code changes
      run: |
        if ! git diff --cached --exit-code; then 
          git config --global user.email "gunnar_ronneberg@yahoo.no"
          git config --global user.name "gunnarro"
          git commit -m "github action updated microservice template"
          git push https://gunnarro:$GITHUB_TOKEN@github.com/gunnarro/spring-boot-microservice-template.git
        else
          echo "nothing to commit"
        fi
        
#    - name: Test microservice template
#      run: mvn --quiet -B clean install -f pom.xml
